apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator
  namespace: vault
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-operator
  name: etcd-operator
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-operator
  template:
    metadata:
      labels:
        app: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/travelaudience/etcd-operator:0.7.0-gcs
        imagePullPolicy: Always
        command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      serviceAccountName: etcd-operator
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-backup-operator
  name: etcd-backup-operator
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-backup-operator
  template:
    metadata:
      labels:
        app: etcd-backup-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/travelaudience/etcd-operator:0.7.0-gcs
        imagePullPolicy: Always
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      serviceAccountName: etcd-operator
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd-restore-operator
  name: etcd-restore-operator
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-restore-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/travelaudience/etcd-operator:0.7.0-gcs
        imagePullPolicy: Always
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: "etcd-restore-operator:19999"
      serviceAccountName: etcd-operator
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-restore-operator
  namespace: vault
spec:
  selector:
    app: etcd-restore-operator
  ports:
  - protocol: TCP
    port: 19999
