apiVersion: v1
kind: Namespace
metadata:
  name: kube-lego
---
apiVersion: v1
data: 
  lego.email: john.doe@example.com
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
metadata: 
  name: kube-lego
  namespace: kube-lego
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: kube-lego
  namespace: kube-lego
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: kube-lego
    spec: 
      containers:
        - env: 
            - name: LEGO_LOG_LEVEL
              value: info
            - name: LEGO_EMAIL
              valueFrom: 
                configMapKeyRef: 
                  key: lego.email
                  name: kube-lego
            - name: LEGO_URL
              valueFrom: 
                configMapKeyRef: 
                  key: lego.url
                  name: kube-lego
            - name: LEGO_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
            - name: LEGO_POD_IP
              valueFrom: 
                fieldRef: 
                  fieldPath: status.podIP
          image: "jetstack/kube-lego:0.1.5"
          imagePullPolicy: Always
          name: kube-lego
          ports: 
            - containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
