apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
data:
  config.hcl: |
      api_addr     = "https://vault.example.com"
      cluster_addr = "http://vault:8201"

      listener "tcp" {
        address         = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable     = 1
      }

      storage "etcd" {
        address         = "https://etcd-client.vault.svc.cluster.local:2379"
        etcd_api        = "v3"
        ha_enabled      = "true"
        path            = "vault/"
        sync            = "false"
        tls_ca_file     = "/vault/tls/vault-ca.crt"
        tls_cert_file   = "/vault/tls/vault.crt"
        tls_key_file    = "/vault/tls/vault.key"
      }
