apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
data:
  config.hcl: |
      listener "tcp" {
        address         = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable     = 1
      }

      storage "etcd" {
        address         = "https://etcd-vault-client.etcd.svc.cluster.local:2379"
        cluster_addr    = "http://vault:8201"
        etcd_api        = "v3"
        ha_enabled      = "true"
        path            = "vault/"
        redirect_addr   = "https://vault.example.com"
        sync            = "false"
        tls_ca_file     = "/vault/tls/vault-etcd-ca.crt"
        tls_cert_file   = "/vault/tls/vault-etcd.crt"
        tls_key_file    = "/vault/tls/vault-etcd.key"
      }
