apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
spec:
  ports:
  - name: vault-api
    port: 8200
  - name: vault-clustering
    port: 8201
  clusterIP: None
  selector:
    app: vault
